blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/MiguVT/Timeconverter/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/MiguVT/Timeconverter#readme
    about: Check out the project documentation
